const { Octokit } = require('@octokit/rest');

async function summarizePR() {
  // Initialize Octokit client
  const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

  const owner = process.env.REPO_OWNER;
  const repo = process.env.REPO_NAME;
  const prNumber = parseInt(process.env.PR_NUMBER);

  try {
    console.log(`Fetching PR #${prNumber} from ${owner}/${repo}...`);

    // Fetch PR details
    const { data: pr } = await octokit.pulls.get({
      owner,
      repo,
      pull_number: prNumber,
    });

    // Fetch PR files (paginated for large PRs)
    const files = await octokit.paginate(octokit.pulls.listFiles, {
      owner,
      repo,
      pull_number: prNumber,
      per_page: 100,
    });

    console.log(`Found ${files.length} files changed`);

    // Prepare context for the AI
    const filesChanged = files.map(f => ({
      filename: f.filename,
      status: f.status,
      additions: f.additions,
      deletions: f.deletions,
      changes: f.changes,
    }));

    // For large PRs, build diff from file patches instead of full diff
    let diffContent = '';
    let totalDiffSize = 0;
    const maxDiffSize = 20000; // characters

    for (const file of files) {
      if (file.patch) {
        const fileDiff = `diff --git a/${file.filename} b/${file.filename}\n${file.patch}\n`;

        // Only include if we haven't exceeded size limit
        if (totalDiffSize + fileDiff.length < maxDiffSize) {
          diffContent += fileDiff;
          totalDiffSize += fileDiff.length;
        } else {
          // Indicate that we truncated
          diffContent += '\n... (additional changes truncated for size)';
          break;
        }
      }
    }

    // If no patches available (binary files, etc.), note that
    if (!diffContent) {
      diffContent = '(Binary files or changes without text diff)';
    }

    const prompt = `Please analyze this pull request and provide a comprehensive summary.

**PR Title:** ${pr.title}

**PR Description:**
${pr.body || 'No description provided'}

**Files Changed (${files.length} files):**
${filesChanged.slice(0, 50).map(f => `- ${f.filename} (${f.status}, +${f.additions}/-${f.deletions})`).join('\n')}
${files.length > 50 ? `\n... and ${files.length - 50} more files` : ''}

**Code Changes:**
\`\`\`diff
${diffContent}
\`\`\`

Please provide:
1. **Summary** - A concise overview of what this PR does (2-3 sentences)
2. **Key Changes** - Main modifications broken down by component/area
3. **Impact** - What systems/features are affected
4. **Potential Concerns** - Any risks, breaking changes, or areas that need careful review (if applicable)

Format your response clearly with markdown headers and bullet points.`;

    console.log('Generating summary with GitHub Models (GPT-4o-mini)...');

    // Call GitHub Models API (FREE)
    const response = await fetch('https://models.inference.ai.azure.com/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messages: [
          {
            role: 'system',
            content: 'You are a helpful code review assistant that provides clear, concise pull request summaries.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        model: 'gpt-4o-mini',
        temperature: 0.7,
        max_tokens: 2000,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`GitHub Models API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    const summary = data.choices[0].message.content;

    // Post comment to PR
    console.log('Posting summary to PR...');
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: `## 🤖 AI-Generated PR Summary

${summary}

---
*Summary generated by GPT-4o-mini via GitHub Models (FREE)*`,
    });

    console.log('✅ Summary posted successfully!');
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

summarizePR();